# CodeRabbit Configuration
# Uses default settings with minimal customization
# Documentation: https://docs.coderabbit.ai/guides/configure-coderabbit

reviews:
  path_filters:
    - '**/src/**'
    - 'package.json'
    - '*config.js'
    - '*config.ts'
    - '*config.json'
    - 'vitest.setup.ts'
    - '!src/routes/debug/**'
