import type { Component } from '$lib';

export interface StyleProcessor<K = Component> {
    /**
     * Processes a part of the component's data to generate styles.
     * @param data The specific data part (e.g., appearance, text properties) needed by this processor.
     * @returns A record of CSS style properties generated by this processor.
     */
    process(data: K): Record<string, any>;
} 